### ISSUE TITLE
put the camera on specific position?

### ISSUE THREAD

**Issue by danielcv-dev** [OVR-Platform/unity-sdk#1]
Hello everyone!!! 
isn't an issue, but is a question... some one knows whether the plugin in unity have a script to put the camera in specific position when the ovr app begins?

Thanks and regards

**Comment by Carlo-Gezapp** [comment]
Good morning.

Through the OVER Unity SDK you have the ability to publish an AR content inside your hexagon. 
The published prefab will be placed exactly in the center of the selected Land. So we suggest to develop your content keeping the main prefab at coordinates 0,0,0.

By living the geo-localized experience you will be positioned according to your real position in the world.

If you live the experience remotely there is no possibility to choose the starting point of the experience, but you will start approximately at the center of the hexagon.

We will consider the proposal of inserting SpawnPoints from Unity SDK to control the starting position of the experience, if visited remotely.

I kindly ask you to update the sdk to version 0.0.2, where you will be able to understand the size of your hexagon.
