### ISSUE TITLE
OVRAsset script problem.

### ISSUE THREAD

**Issue by ergitabi** [OVR-Platform/unity-sdk#2]
Hello,
I have problem in the step in "creating project" window, choocing prefab. There are only 2 items in the window: . 1-None and 2- OvrPlayer Simulator. When I choose "none" it's saying "I must choose a prefab". When I choose "ovr player simulator" and click "publish" it's saying "Prefab does not contain OvrAsset script". So I'm stuck in this point. (P.S.: I have experience 3D software such as 3DS Max, Blender etc but I have never used Unity. I watched a few tutorial but it's not helping me to solve or find out what is the problem.)
Thanks in advance for your help.
Ergun
![Unity problem](https://user-images.githubusercontent.com/100512499/156171412-e0c5d5aa-8c20-40ee-a0c4-da0252fd16d1.jpg)

**Comment by FerBcnHD** [comment]
I solved this problem creating my own Prefab and attaching the OvrAsset script to it.

**Comment by Carlo-Gezapp** [comment]
Good morning.
I kindly ask you to update the sdk to version to 0.0.2. 

Under prefab the OVER Unity SDK expects a prefab saved within the project to be assigned.

This can be done by clicking on the small button on the right and selecting the correct element, or by directly dragging the element into the required field.

![immagine](https://user-images.githubusercontent.com/72753612/165939097-cd755172-8532-47ac-9761-5180994965e3.png)
![immagine](https://user-images.githubusercontent.com/72753612/165939327-ad8a78db-83c2-4b94-ab8c-a7d31d487ad7.png)

The selected prefab must be the prefab containing the experience you want to publish. The prefab, to be validated, must have the OvrAsset component assigned to itself.

![immagine](https://user-images.githubusercontent.com/72753612/165940623-936fbe28-1527-4e34-8459-628f445a2464.png)
