### ISSUE TITLE
File unity package missing

### ISSUE THREAD

**Issue by DavideRiccitiello** [OVR-Platform/unity-sdk#3]
You should insert the alpha unity package also here. Comfortable for us developers 
![image](https://user-images.githubusercontent.com/29292013/156766987-07b8977e-604e-4663-97f1-ad5512027adf.png)

**Comment by DavideRiccitiello** [comment]
You could have inserted the unity package outside the zip file, as well with the Readme.txt file. Having a zip file as Unity package wirtten SourceCode is misleding. Just giving a clear direction of what the file is without having to download it and open it

**Comment by pdxmusic** [comment]
We added the link! Thanks for your suggestion.
