### ISSUE TITLE
I get this error when I load

### ISSUE THREAD

**Issue by omunegr22** [OVR-Platform/unity-sdk#4]
![WhatsApp Image 2022-03-17 at 11 23 16 AM](https://user-images.githubusercontent.com/101804416/158797575-3d2f643f-4cbc-42ab-ab7d-62349ad4f29c.jpeg)

I uploaded my Unity project on OVR but this is what I get when I try to launch it

Any ideas ?

**Comment by FerBcnHD** [comment]
Same error for me.

**Comment by Carlo-Gezapp** [comment]
Good morning.
I kindly ask you to update the sdk to version to 0.0.2. Several bug fixes have been made.

We have also removed the project creation via the OVER Unity SDK. 

There is no possibility to rework a Unity project on the OVER Web Builder
