### ISSUE TITLE
Errors in unity console when publishing

### ISSUE THREAD

**Issue by omunegr22** [OVR-Platform/unity-sdk#5]
![14](https://user-images.githubusercontent.com/101804416/158805410-f104efa0-fcad-4ec9-818a-479a701120c3.PNG)
![13](https://user-images.githubusercontent.com/101804416/158805415-437dd141-5bba-42f6-8c48-529f5c2f8d48.PNG)
![15](https://user-images.githubusercontent.com/101804416/158805417-e4d2fcd4-5de3-4c0e-8899-87893af5eec4.PNG)

I get these error when I try to publish something

**Comment by FerBcnHD** [comment]
I had the same problem. 
In my case I was missing Unity IOS build modules.

**Comment by Carlo-Gezapp** [comment]
Good morning.
I kindly ask you to update the sdk to version to 0.0.2. Several bug fixes have been made.
Please let us know if the problem persists.
